#!/usr/bin/env bash
#Write a Bash script that displays To infinity and beyond indefinitely.

_term() {
	echo "I am invincible!!!"
}

i=1
while (( $i ))
do
	echo "To infinity and beyond indefinitely"
	sleep 2
	trap _term SIGTERM
done
