#!/usr/bin/env bash
#Write a Bash script that displays the time for 12 hours and 59 minutes:
#display hours from 0 to 12
#display minutes from 1 to 59

min=1
hour=0

while [[ $hour -le 12 ]]
do
	echo "Hour: $hour"
	while [[ $min -lt 60 ]]
	do
		echo "$min"
		min=$(( min + 1 ))
	done
	min=1
	hour=$(( hour + 1))
done
