#!/usr/bin/env bash 
#Write a Bash script that displays:
#The content of the current directory
#In a list format
#Where only the part of the name after the first dash is displayed
LIST="$(ls)"
for file in $LIST
do
	name=$(echo "$file" | cut -d "-" -f 2)
	echo "$name"
done
